Server:
  host: " 0.0.0.0"  # | both have to be changed by running
  port: 5001        # | flask run -h {host} -p {port}
  statusPage: 'status'

ReturnCodes:
  working:
    code: 0 #return code of the bash script
    message: "Service up and runnning" #optional html message displayed
    html: 200 #html return code, important for eg. uptime coomer
  error:
    code: 1
    message: "Service unreachable"
    html: 501


Scripts:
  default:
    exec: "/bin/bash" #executable used, eg bash for a script  
    name: "default" #name by which the api call is made
    path: "scripts/defaultTest.sh" #path of the file as seen by the flask app