Server:
  host: " 0.0.0.0"  # | both have to be changed by running
  port: 5001        # | flask run -h {host} -p {port}, NOT WORKING CURRENTLY
  statusPage: 'status'

ReturnCodes:
  working:
    #return code of the script
    code: 0 
    #optional html message returned
    message: "Service up and runnning" 
    #html return code, important for eg. uptime kumar
    html: 200 
  error:
    code: 1
    message: "Service unreachable"
    html: 501


Scripts:
  # A short description
  # This script tests the basic functionality
  default:
    # whether the script is enabled or not
    enabled: true
    # executable used, eg bash for a script       
    exec: "/bin/bash" 
    # name by which the api call is made appended to "{statusPage}/"
    name: "default" 
    # path of the script as seen by the flask app
    path: "scripts/defaultTest.sh" 